### ISSUE TITLE
Base: Revise monitor and deploy script

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#123]
[scripts/iota_deploy](https://github.com/wunder3605/iri/blob/dev/scripts/iota_deploy/iota_deploy.py) provides an elegant implementation to deploy IRI instances. We shall refactor the current methods to ensure consistent deployment.

Expected output:
1. Every full node has the same file system hierarchy;
2. New deploy script can be applied for each full node;
3. Run IRI instances after proper trigger;

TODO:
- [x] Monitor exporter base on [iota-prom-exporter](https://github.com/crholliday/iota-prom-exporter)
- [x] AlertManager, issue #139 
- Deploy and testing on node0
  - [x] Deploy Prometheus framewok
  - [x] Deploy Rundeck framework
  - [x] Write a sample Rundeck job
  - [x] Write a sample ansible-playbook job
  - [x] User guide: IOTA full-node management framework
    - Refer to: [How to deploy IRI](https://github.com/DLTcollab/iri-playbook/wiki)

Output documentation (WIP):
- [Prometheus deploy note](https://hackmd.io/s/BJoJXTiB4)
- [Ansible deploy note](https://hackmd.io/s/Sk0ED4RLE)
- [Rundeck deploy note](https://hackmd.io/s/BJblNdlt4)
  - [Integrate with Ansible playbook](https://hackmd.io/s/BkOPR59i4)
- [User guide: IOTA full-node management framework](https://hackmd.io/s/rJl7wJm94)

**Comment by yillkid** [comment]
## Legacy monitors and deploy script architecture:
![delme](https://user-images.githubusercontent.com/185872/52908715-38ce6d80-32b6-11e9-9aac-6d097053b6e5.png)

IOTA full-node and Tangle-accelerator monitoring solution:

## Introduction

Monitor and deploy Full-node and Tangle-accelerator and manage service logs on Prometheus platform.

Including

- Monitor all Full-node and Tangle-accelerator of DLTcolab 
- Manage monitor and deploy scripts
- Manage monitor and deploy log in the database

Not including

- Data Visualization

## Architectore
![](https://i.imgur.com/JvMsbUe.png)
[edit me ...](https://docs.google.com/drawings/d/1NRk6CvFvDvGTgr3-_A4f15JRs74deamrxyF3xpTEYqA/edit?usp=sharing)


## Prometheus Exporters

#### Server exporters:
- ICMP ping
- IRI
  - Versions 
  - launch parameter
    - dcurl
- RocksDB
  - Versions  

#### Full-node exporters:
- GetNodeInfo
  - Response (success/limit from remote)
  - latestSolidSubtangleMilestoneIndex/latestMilestoneIndex 
- Broadcast
  - Response (success/limit from remote)
  - Duration
- GetNeighborInfo
  - Remove Dead neighbors
  - Neighbor number alert 
- GetTransactionToApprove
  - Response (success/limit from remote)  
  - Duration

#### Deploy scripts:
- Start/restart/stop system service
- Revise neighbor list
- Revise load balancing backend
  - full-node
  - tangle accelerator 

#### Tangle-accelerator exporters:
- Send_transfer API 

## Reference
- [Prometheus](https://prometheus.io/)

**Comment by yillkid** [comment]
[Prometheus deploy note](https://hackmd.io/s/BJoJXTiB4)

TODO:
- [ ] Monitor exporter base on [iota-prom-exporter](https://github.com/crholliday/iota-prom-exporter)

**Comment by yillkid** [comment]
![](https://i.imgur.com/XLVAzQa.png)

![temp](https://user-images.githubusercontent.com/185872/53709472-75cc5f80-3e73-11e9-9699-0ac1cb281c9a.png)

Deploy scripts (notify webhook):
- Start/restart/stop system service
- Revise neighbor list
- Revise load balancing backend
  - full-node
  - tangle accelerator

**Comment by yillkid** [comment]
![](https://i.imgur.com/XLVAzQa.png)

![temp](https://user-images.githubusercontent.com/185872/53709472-75cc5f80-3e73-11e9-9699-0ac1cb281c9a.png)

Deploy scripts (notify webhook):
- Start/restart/stop system service
- Revise neighbor list
- Revise load balancing backend
  - full-node
  - tangle accelerator

**Comment by yillkid** [comment]
#### Notify protocol

![notify](https://user-images.githubusercontent.com/185872/53888710-2ac36f80-4060-11e9-90e9-1c97a3803584.png)

**Comment by yillkid** [comment]
#### Notification flow (ver. 2)
![notify_1](https://user-images.githubusercontent.com/185872/54081907-ec6fce00-4347-11e9-9b17-542de6fb18f5.png)
#### 
- [Prometheus alert (webhook) deploy note](https://hackmd.io/FJNI8iz1SY24Z1Zyg2faXg?view#Alert---webhook)
- [Ansible seploy note](https://hackmd.io/YjH_mujdSCGCzRaulQmn-Q?view)
- [Ansijet](https://github.com/hiddentao/ansijet)

**Comment by wusyong** [comment]
I think this issue is too large to track off. Maybe @yillkid can open some minor issue and reference them from here.

**Comment by yillkid** [comment]
Got a dependency issue (build gulp with node@v11.12.0) when deploy Ansijet, reproduct flow as below:
#### Write and test Ansible-playbook on `node0`
  - ``` $ cd /home/ubuntu/ansible-fullnode```
  - ``` $ vi fullnode.yml```
```
- hosts: fullnode
  become: true  # use sudo
  tasks:
    - name: install vim
      apt: name=vim update_cache=yes state=latest
```
  - ```$ ansible-playbook fullnode.yml```
```
PLAY [fullnode] ********************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [node.deviceproof.org]

TASK [install vim] *****************************************************************************************************************************************************
ok: [node.deviceproof.org]

PLAY RECAP *************************************************************************************************************************************************************
node.deviceproof.org       : ok=2    changed=0    unreachable=0    failed=0   
```

#### Upgrade nodejs to 11.2
- Refer [https://github.com/tj/n](https://github.com/tj/n)

#### Install Ansijet
```
$ git clone https://github.com/hiddentao/ansijet.git ansijet
$ cd ansijet
$ npm install -g gulp bower
$ npm install
$ bower install
$ npm run build
```

Output
```
$ npm run build

> ansijet@1.2.0 build /home/ubuntu/ansible-fullnode/ansijet
> node --harmony `which gulp` build

evalmachine.<anonymous>:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at evalmachine.<anonymous>:25:1
    at Object.<anonymous> (/home/ubuntu/ansible-fullnode/ansijet/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/ubuntu/ansible-fullnode/ansijet/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ansijet@1.2.0 build: `node --harmony `which gulp` build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ansijet@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-03-24T07_47_41_882Z-debug.log
```

#### Workaround (not work)
- After update to Node 11.0.0 running Gulp exits with 'ReferenceError: internalBinding is not defined' [#2246](https://github.com/gulpjs/gulp/issues/2246)

```
$ npm view natives version
1.1.6
```

**Comment by ender503** [comment]
Maybe we should evaluate another solution.
The Ansijet latest updated is at `6 Nov 2014`, it seems like not maintain anymore.
And it has lots of vulnerabilities.
```
added 943 packages from 248 contributors and audited 1701 packages in 51.826s
found 128 vulnerabilities (55 low, 46 moderate, 26 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by ender503** [comment]
@yillkid  Prometheus can be integrated with the following services, we could consider them.
https://victorops.com
https://www.pagerduty.com
https://www.opsgenie.com

**Comment by yillkid** [comment]
Evaluating [RUNDECK](https://www.rundeck.com/what-is-rundeck):

## Standard Operating Procedures
![image](https://user-images.githubusercontent.com/185872/55211272-33096780-5226-11e9-8638-3bb2a3dee8d7.png)
![image](https://user-images.githubusercontent.com/185872/55211275-36045800-5226-11e9-84e2-89be6e20b0f3.png)
![image](https://user-images.githubusercontent.com/185872/55211285-3866b200-5226-11e9-8288-717ff08cf5a6.png)
![image](https://user-images.githubusercontent.com/185872/55211286-3b61a280-5226-11e9-9c9b-639adca00a24.png)
![image](https://user-images.githubusercontent.com/185872/55211289-3dc3fc80-5226-11e9-8554-786d96d2dd70.png)

## Dashboard
![image](https://user-images.githubusercontent.com/185872/55211299-46b4ce00-5226-11e9-8ae9-9138279c1a92.png)

## Basic usage

#### Node Execution
- [SSH](https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html)

#### Job
- Creating jobs
    - [Creating a job GUI](https://docs.rundeck.com/docs/manual/creating-jobs.html)
- Running a Job
  - [REST API](https://docs.rundeck.com/docs/api/#running-a-job)

## Rundeck ansible integration
![image](https://user-images.githubusercontent.com/185872/55211362-98f5ef00-5226-11e9-8d69-e06271fc2833.png)

## Reference
- [Rundeck](https://www.rundeck.com/)
- [Rundeck makes Ansible even better](https://www.rundeck.com/ansible)
- [RunDeck——Web界面的運維控制台](https://my.oschina.net/fitnessefan/blog/425682)

**Comment by ender503** [comment]
@yillkid please discuss the solution to the #139 .
This thread is too long.

**Comment by yillkid** [comment]
Since we choice [iri-playbook](https://github.com/DLTcollab/iri-playbook) as the deploy framework. We can close this issue and focus on the Ansible role and playbook development dor DevOps.
