### ISSUE TITLE
Monitor rule - Health check for IOTA full-node

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#154]
##  Health check for IOTA full-node
A monitor rule hosts on Prometheus, Rundeck, and Ansible, the workflow as below:
- Health check for Host server by [blackbox_exporter](https://github.com/prometheus/blackbox_exporter)
- Health check for IOTA full-node by [iota-prom-exporter](https://github.com/crholliday/iota-prom-exporter)

#### Architecture and WorkFlow:
![Arc](https://user-images.githubusercontent.com/185872/58391430-7d616600-8068-11e9-94eb-267ecca6c9b7.png)
[Edit me ...](https://docs.google.com/drawings/d/1VcRazLn0O7RlFWGorePAe14hBZ92u22XGrnJE-Rb7Tw/edit?usp=sharing)

#### Output documentation:
Work In Process

#### TODOs:
- [iota-prom-exporter](https://github.com/crholliday/iota-prom-exporter)
  - [ ] GetNodeInfo
    - [ ] Response (success/limit from remote)
    - [ ] latestSolidSubtangleMilestoneIndex/latestMilestoneIndex
  - [ ] Broadcast
    - [ ] Response (success/limit from remote)
    - [ ] Duration
  - [ ] GetNeighborInfo
    - [ ] Remove Dead neighbors
    - [ ] Neighbor number alert
  - [ ] GetTransactionToApprove
    - [ ] Response (success/limit from remote)
    - [ ] Duration

#### Reference:
- [Prometheus deploy note](https://hackmd.io/s/BJoJXTiB4)
- [Ansible deploy note](https://hackmd.io/s/Sk0ED4RLE)
- [Rundeck deploy note](https://hackmd.io/s/BJblNdlt4)
  - [Integrate with Ansible playbook](https://hackmd.io/s/BkOPR59i4)

**Comment by ender503** [comment]
![image](https://user-images.githubusercontent.com/1849431/59012185-70632480-8869-11e9-81ba-de6e3fea844e.png)

The Grafana will send the notification to the Slack channel if `coordinator_milestone - subtangle_milestone > 1`.
