### ISSUE TITLE
Permanode: seek for alternatives

### ISSUE THREAD

**Issue by wusyong** [DLTcollab/general#176]
As permanode is still under developing, we might need to find alternative in short term to help commercial usage. One of possible solution is distributed database deployment. With permanode using scyllaDB, we shall also adapt to it and integrate to TA or cIRI/IRI. Or maybe it can be a microservice!

Here are some references might help:
- ScyllaDB documentation: https://docs.scylladb.com/
- CQL C/C++ driver: http://datastax.github.io/cpp-driver/

- [x] [ScyllaDB Feasibility Study](https://github.com/dltcollab/general/issues/177)
- [x] [Introduce ScyllaDB to TA](https://github.com/dltcollab/tangle-accelerator/issues/248)
- [x] [ScyllaDB API interface](https://github.com/dltcollab/tangle-accelerator/issues/260)
- [x] [using ZeroMQ to subscribe confirmed transaction](https://github.com/dltcollab/general/issues/197)
- [ ] [Scylla nodes building](https://github.com/DLTcollab/tangle-accelerator/issues/261) 
- [ ] [Scalability testing](https://github.com/dltcollab/general/issues/196)

**Comment by jserv** [comment]
@locke2833, Let's close these issues since we made explicit decisions already.

**Comment by locke2833** [comment]
We use IF Chronicle as a part of our Permanode solution.
