### ISSUE TITLE
Base: Upgrade IRI to 1.8.0-COACH

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#180]
Upgrade IRI from 1.7.0-COACH to 1.8.0-COACH:

## Action items
- [x] Deploy to every node (braking upgrade)
- [x] Deploy with DltColLab [iri-playbook](https://github.com/dltcollab/iri-playbook)

#### Auto-tethering nodes maintain by IF:
IOTA foundation provides 3 auto-tethering nodes.

```
tcp://auto01.iota-tangle.io:15666 tcp://auto02.iota-tangle.io:15666 tcp://auto03.iota-tangle.io:15666
```

#### MAX_PEERS:
Defines the max number of connected neighbor. Default 5.

#### Batching saturation ratio:
- [Batched Binary Encoded Ternary Curl](https://github.com/luca-moser/bct_curl)

```
$ sudo journalctl -u iri | grep batching saturation ratio 

07/11 18:21:46.099 [pool-11-thread-1] INFO  BatchedBCTCurl:103 - batching saturation ratio 7.0% (processed 520 / max possible 7424), cycles 116, avg. cycle time 175.0ms
```

- batching saturation ratio: how many of the available slots were actually filled in the last 20 seconds given the amount of cycles which were done.
- processed: how many transactions were actually hashed
- max possible: how many transactions could have been batched given the amount of cycles done (116 *64)
- cycles: how many hashing cycles were done
- avg. cycle time: the average time each batching cycle took from the first transaction which arrived at the hashing being finished

## Documentation
- [How to deploy IRI](https://github.com/DLTcollab/iri-playbook/wiki#how-to-deploy-iri)

## TODO
- [x] Avoid expose hosts and groups definition [#5](https://github.com/DLTcollab/iri-playbook/pull/5)
- [x] Add 3 auto-tethering nodes of default neighbor list [#6](https://github.com/DLTcollab/iri-playbook/pull/6)
- [x] Set maximum number of neighbors to 20 [#8](https://github.com/DLTcollab/iri-playbook/pull/8)
- [x] Set remote limit API accessable on localhost [#9](https://github.com/DLTcollab/iri-playbook/pull/9)
- [x] Update new configuration to all nodes
