### ISSUE TITLE
Infra: Integrate NCKU servers

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#186]
We plan to integrate all NCKU servers in one place for deploying the IOTA backend service:
1. Load balancing for FPGA accelerator 
2. Load balancing for IOTA full-node
3. Easier to maintain

## Architecture
![Arch](https://user-images.githubusercontent.com/185872/61512529-d1674600-aa2c-11e9-8545-1bf2777f32d9.png)
- [Source](https://docs.google.com/drawings/d/1scFQR6NTEkcxuYjpb0WbISquC_jhmISMhYYLMrQJOPM/edit?usp=sharing)

## TODO:
- [x] Smart Plug for FPGA board (step 1), #184
  - [x] Node1
- [x] Buy de10 nano (8 pieces), #187 
  - [x] Setup router and switch for NCKU #209
- [x] Area and facilities application
  - [x] Move node1 and FPGA boards into server cabinet #230 
- [x] Buy one advanced router, #201
  - Block by area and facilities application
- [x] Integrate all servers
  - [x] Integrate Node0 to 8F server cabinet #231 
  - [x] Integrate devorg to 8F server cabinet
- [x] Deploy FPGA boards with multi-IRI nodes

**Comment by jserv** [comment]
@yillkid, make the progress transparent and up-to-date.

**Comment by yillkid** [comment]
The de10 nano (8 pieces) have arrival to NCKU on 2019-08-06, will set up with full-node (node1, node10)  with @marktwtn.
