### ISSUE TITLE
Infra: node8 (NCTU) service activation

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#206]
#### We got 10GB RAM temporarily
$ free -g
![image](https://user-images.githubusercontent.com/185872/63834742-969bea80-c9a8-11e9-9741-0b9826b6645f.png)

## TODO
- [x] Enable IRI service
- [x] Interact with node10
- [x] set up the handover mechanism at NCTU

**Comment by jserv** [comment]
We shall introduce the unified account management among existing machines for maintenance purpose.

**Comment by yillkid** [comment]
We use [OpenVPN](https://openvpn.net/) to manage the remote access user. We will delete someone's certificate if we think he/she not suitable to access any services behind the VM anymore. 

![ac](https://user-images.githubusercontent.com/185872/68368378-e64e1d80-0172-11ea-8046-645df909a5fc.png)

For now, we still can't:
1. Management of the SSH public keys in `authorized_keys` file of VM.
2. We still can't clear the SSH keys if someone is dropped by VPN service.

We can use the Ansible [authorized_key_module](https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html) to manage the public key. I will create a new issue to trace it.
