### ISSUE TITLE
Upgrade Trinity wallet and checking the balance

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#240]
On February 12, 2020 the Trinity Wallet was attacked via a third-party dependency from Moonpay, which resulted in the theft of around 8.55 Ti in IOTA tokens. We should:

- Action items
  - [x] Upgrade Trinity wallet of BiiLabs/DLTcolLab #241 
  - [x] Migration IOTA seed #242
  - [x] Check all balance in Trinity wallet and Exchange #243
  - [x] Update and release the [issue report](https://hackmd.io/v-Q1A1L4RoS_t7kMZ6BFyg)
- Reference
  - [IOTA coordinator halt on 2020-02-13](https://hackmd.io/v-Q1A1L4RoS_t7kMZ6BFyg)
  - [Trinity Attack Incident Part 1: Summary and next steps](https://blog.iota.org/trinity-attack-incident-part-1-summary-and-next-steps-8c7ccc4d81e8)
  - [Trinity Attack Incident Part 2: Trinity Seed Migration Plan](https://blog.iota.org/trinity-attack-incident-part-2-trinity-seed-migration-plan-4c52086699b6)
  - [Trinity Attack Incident Part 3: Key Learnings & Takeaways](https://blog.iota.org/trinity-attack-incident-part-3-key-learnings-takeaways-c933de22fd0a)
